name: Generate Docs

on:
  push:
    branches:
      - "master"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NotEnoughUpdates'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn --immutable 

      - name: Generate Docs
        run: yarn typedoc src/index.ts

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs