name: Publish dev
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
jobs:
  npm-publish:
    name: npm publish
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NotEnoughUpdates'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Check previous released version
        id: pre-release
        run: |
          if [[ $(npm view @notenoughupdates/discord-akairo@dev version | grep -e "$(jq --raw-output '.version' package.json).*.$(git rev-parse --short HEAD | cut -b1-3)") ]]; \
          then echo '::set-output name=release::false'; \
          else echo '::set-output name=release::true'; fi

      - name: Install dependencies
        if: steps.pre-release.outputs.release == 'true'
        run: yarn --immutable

      - name: Publish package
        if: steps.pre-release.outputs.release == 'true'
        run: |
          npm version --git-tag-version=false $(jq --raw-output '.version' package.json).$(date +%s).$(git rev-parse --short HEAD)
          npm publish --tag dev || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}